#################################################################
#                                                               #
#                        BEAVER PLUGIN                          #
#                    Developed by ccoding                       #
#          GitHub: https://github.com/devkopi                   #
#                                                               #
#################################################################

# Beaver configuration file
# Documentation: https://github.com/devkopi/Beaver

debug-mode: false

motd:
  enabled: true

  normal:
    - "&6&lBeaver &fMotd Normal"
    - "&7Thanks for using the plugin!"

  maintenance:
    - "&6&lBeaver &7» &cServer under maintenance"
    - "&7Please come back later."

discord:
  enabled: true
  webhook-url: "LINK_WEBHOOK_HERE"
  send-embed: true